# This is a basic workflow to help you get started with Actions

name: Fork Using API
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:  
  fork-repo:    
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create Fork Request
        run: |
          PR_URL=$(curl \
            -X POST \
            -H "Authorization: token ${{secrets.KYN_GIT_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/rajeshr340/az-terraform-iac/forks \
            -d '{
              "name": "az-terraform-iac-2",
              "default_branch_only": "false"}')
          echo "Fork Details L: $PR_URL"
