name: Fork Using API
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:  
  fork-repo:    
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create Fork Request
        run: |
          echo ${{github.ref}}
          echo ${{toJson(github)}}
          PR_URL=$(curl \
            -X POST \
            -H "Authorization: token ${{secrets.KYN_GIT_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/rajeshr340/az-terraform-iac/forks \
            -d '{
              "name": "az-terraform-iac-2",
              "default_branch_only": "false",
              "ref": "${{github.ref}}"}')
          echo "Fork Details L: $PR_URL"
