name: Fork to Enterprise GitHub

on:
  workflow_dispatch: 

jobs:
  fork-to-enterprise:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fork repository to Enterprise GitHub
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        ENTERPRISE_USERNAME="cloud-practice-engineering"
        ENTERPRISE_REPO_NAME="az-terraform-iac"

        # Fork the repository using gh with the provided GitHub token
        gh repo fork rajeshr340/az-terraform-iac --clone --remote=enterprise

        # Update the remote URL to the Enterprise GitHub repository
        git remote set-url enterprise "https://github.kyndryl.ne/$ENTERPRISE_USERNAME/$ENTERPRISE_REPO_NAME.git"

        # Push changes to the Enterprise GitHub repository
        git push -u enterprise HEAD

    - name: Print Enterprise repository URL
      run: |
        ENTERPRISE_REPO_NAME="your-enterprise-repo-name"
        echo "Forked repository URL: https://github.com/$ENTERPRISE_USERNAME/$ENTERPRISE_REPO_NAME"
