name: Fork to Organization

on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 

jobs:
  fork-to-organization:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fork to Organization
      run: |
        gh repo fork --org cloud-practice-engineering --clone
      env:
        GITHUB_TOKEN: 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


