name: Fork to Organization

on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 

jobs:
  fork-to-organization:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Authenticate with gh
      run: gh auth login -p https -h github.kyndryl.net --with-token <<< ${{ secrets.KYN_GIT_PAT }}

    - name: Fork to Organization
      run: |
        gh repo fork --org SNOW-Digital-IMI --clone
      #env:
      #  GITHUB_TOKEN: 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


